/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Chair.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chair.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.099, 0]} rotation={[Math.PI, 0, Math.PI]} scale={0.734}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.BlackPlastic} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['BlackPlastic.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.ClothBlack} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.BaseMetal} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['BlackPlastic.002']} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Plane.geometry} material={materials.T_Computer} position={[0, 0.009, 0.009]} scale={[0.252, 0.252, 0.168]} />
      <group scale={0.01}>
        <mesh geometry={nodes.pCube4_Handles_and_support_0.geometry} material={materials.Handles_and_support} />
        <mesh geometry={nodes.pCylinder10_Legs_0.geometry} material={materials.Legs} />
        <mesh geometry={nodes.polySurface217_Wheel_0.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.polySurface222_Wheel_0.geometry} material={materials.Wheel} position={[11.308, 0, -5.141]} />
        <mesh geometry={nodes.polySurface223_Wheel_0.geometry} material={materials.Wheel} position={[-7.157, 0, -7.838]} />
        <mesh geometry={nodes.polySurface224_Wheel_0.geometry} material={materials.Wheel} position={[-1.485, 0, -18.826]} />
        <mesh geometry={nodes.polySurface225_Wheel_0.geometry} material={materials.Wheel} position={[9.853, 0, -16.469]} />
        <mesh geometry={nodes.polySurface44_Back_portion_0.geometry} material={materials.Back_portion} />
        <mesh geometry={nodes.polySurface44_Centre_piece_0.geometry} material={materials.Centre_piece} />
        <mesh geometry={nodes.polySurface44_Chair_eye_0.geometry} material={materials.Chair_eye} />
        <mesh geometry={nodes.polySurface44_Chair_leather_0.geometry} material={materials.Chair_leather} />
        <mesh geometry={nodes.polySurface44_White_portion_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.polySurface50_Centre_piece_0.geometry} material={materials.Centre_piece} />
        <mesh geometry={nodes.polySurface50_Chair_leather_0.geometry} material={materials.Chair_leather} />
        <mesh geometry={nodes.polySurface50_White_portion_0.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/Chair.glb')
