/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Room2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Room2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.015, 0.015, -0.267]} rotation={[Math.PI / 2, 0, 0]} scale={[0.009, 0.008, 0.009]}>
        <mesh geometry={nodes.Hiko_Side_Table.geometry} material={materials.FUNITURE_039_MAT} position={[-101.79, -251.647, 18.712]} scale={[4.404, 3.971, 4.144]} />
      </group>
      <group position={[-0.657, -0.226, 0.002]} rotation={[-Math.PI / 2, 0, -3.13]} scale={[9.498, 10.625, 12.365]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.pCube4_Handles_and_support_0.geometry} material={materials['Handles_and_support.001']} />
          <mesh geometry={nodes.pCylinder10_Legs_0.geometry} material={materials['Legs.001']} />
          <mesh geometry={nodes.polySurface217_Wheel_0.geometry} material={materials['Wheel.001']} />
          <mesh geometry={nodes.polySurface222_Wheel_0.geometry} material={materials['Wheel.001']} position={[11.308, 0, -5.141]} />
          <mesh geometry={nodes.polySurface223_Wheel_0.geometry} material={materials['Wheel.001']} position={[-7.157, 0, -7.838]} />
          <mesh geometry={nodes.polySurface224_Wheel_0.geometry} material={materials['Wheel.001']} position={[-1.485, 0, -18.826]} />
          <mesh geometry={nodes.polySurface225_Wheel_0.geometry} material={materials['Wheel.001']} position={[9.853, 0, -16.469]} />
          <mesh geometry={nodes.polySurface44_Back_portion_0.geometry} material={materials['Back_portion.001']} />
          <mesh geometry={nodes.polySurface44_Centre_piece_0.geometry} material={materials['Centre_piece.001']} />
          <mesh geometry={nodes.polySurface44_Chair_eye_0.geometry} material={materials['Chair_eye.001']} />
          <mesh geometry={nodes.polySurface44_Chair_leather_0.geometry} material={materials['Chair_leather.001']} />
          <mesh geometry={nodes.polySurface44_White_portion_0.geometry} material={materials['material_0.001']} />
          <mesh geometry={nodes.polySurface50_Centre_piece_0.geometry} material={materials['Centre_piece.001']} />
          <mesh geometry={nodes.polySurface50_Chair_leather_0.geometry} material={materials['Chair_leather.001']} />
          <mesh geometry={nodes.polySurface50_White_portion_0.geometry} material={materials['material_0.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['T_Computer.001']} position={[-0.687, 2.758, -2.131]} scale={[0.598, 0.543, 0.336]} />
      <mesh geometry={nodes.textured003.geometry} material={materials['textured_0.003']} position={[0.917, 2.998, -2.871]} rotation={[Math.PI / 2, 0, 0]} scale={[2.295, 2.868, 2.631]} />
    </group>
  )
}

useGLTF.preload('/Room2.glb')
