/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/AvatarYanaWelcome.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useFBX, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function AvatarYanaWelcome({ animation = "Greeting", ...props }) {
  const group = useRef();

 
  const { scene } = useGLTF("models/AvatarYanaWelcome.glb");
 
  const clone = SkeletonUtils.clone(scene);
 
  const { animations: contactAnimation } = useFBX("animations/Greeting.fbx");
  contactAnimation[0].name = "Greeting";

 
  contactAnimation[0].tracks.forEach(track => {
    track.name = track.name.replace("Armature|", "");
  });

 
  const { actions } = useAnimations([contactAnimation[0]], group);

  useEffect(() => {
    if (actions[animation]) {
      actions[animation].reset().fadeIn(0.5).play();
      return () => actions[animation].fadeOut(0.5);
    }
  }, [animation, actions]);
 
  return <primitive ref={group} object={clone} {...props} />;
}

useGLTF.preload("models/AvatarYanaWelcome.glb");
