/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\React\Portfolio_Yana_Naydenova — копия\Portfolio\public\models\68c8604461035c30823dc86c.glb -o C:\React\Portfolio_Yana_Naydenova — копия\Portfolio\src\components\AvatarHero 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function AvatarHero(props) {
  const { scene } = useGLTF('/models/68c8604461035c30823dc86c.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.mesh_0.skeleton} morphTargetDictionary={nodes.mesh_0.morphTargetDictionary} morphTargetInfluences={nodes.mesh_0.morphTargetInfluences} position={[-0.464, 0.003, -0.136]} scale={0} />
      <skinnedMesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.mesh_1.skeleton} morphTargetDictionary={nodes.mesh_1.morphTargetDictionary} morphTargetInfluences={nodes.mesh_1.morphTargetInfluences} position={[-0.464, 0.003, -0.136]} scale={0} />
      <skinnedMesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.mesh_2.skeleton} morphTargetDictionary={nodes.mesh_2.morphTargetDictionary} morphTargetInfluences={nodes.mesh_2.morphTargetInfluences} position={[-0.464, 0.003, -0.136]} scale={0} />
      <skinnedMesh geometry={nodes.mesh_3.geometry} material={materials.M_Hair_60} skeleton={nodes.mesh_3.skeleton} position={[-0.464, 0.003, -0.136]} scale={0} />
      <skinnedMesh geometry={nodes.mesh_4.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.mesh_4.skeleton} position={[-0.464, 0.003, -0.136]} scale={0} />
      <skinnedMesh geometry={nodes.mesh_5.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.mesh_5.skeleton} position={[-0.464, 0.003, -0.136]} scale={0} />
      <skinnedMesh geometry={nodes.mesh_6.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.mesh_6.skeleton} position={[-0.464, 0.003, -0.136]} scale={0} />
      <skinnedMesh geometry={nodes.mesh_7.geometry} material={materials.Wolf3D_Body} skeleton={nodes.mesh_7.skeleton} position={[-0.464, 0.003, -0.136]} scale={0} />
    </group>
  )
}

useGLTF.preload('/models/68c8604461035c30823dc86c.glb')
