/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/AvatarYanaEducation.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useFBX, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function AvatarYanaEducation({ animation = "Typing", ...props }) {
  const group = useRef();

   
  const { scene } = useGLTF("models/AvatarYanaEducation.glb");

  
  const clone = SkeletonUtils.clone(scene);

 
  const { animations: educationAnimation } = useFBX("animations/Typing.fbx");
  educationAnimation[0].name = "Typing";

   
  educationAnimation[0].tracks.forEach((track) => {
    track.name = track.name.replace("Armature|", "");
  });
 
  const { actions } = useAnimations([educationAnimation[0]], group);

  useEffect(() => {
    const action = actions[animation];
    if (action) {
      action.reset().fadeIn(0.5).play();
      return () => action.fadeOut(0.5);
    }
  }, [animation, actions]);

 
  return <primitive ref={group} object={clone} {...props} />;
}

useGLTF.preload("models/AvatarYanaEducation.glb");