/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/AvatarYanaContact.glb 
*/
import React, { useEffect, useRef } from "react";
import { useGLTF, useFBX, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function AvatarYanaContact({ animation = "Thankful", ...props }) {
  const group = useRef();

  
  const { scene } = useGLTF("models/AvatarYanaContact.glb");
 
  const clone = SkeletonUtils.clone(scene);

 
  const { animations: contactAnimation } = useFBX("animations/Thankful.fbx");
  contactAnimation[0].name = "Thankful";

   
  contactAnimation[0].tracks.forEach((track) => {
    track.name = track.name.replace("Armature|", "");
  });

 
  const { actions } = useAnimations([contactAnimation[0]], group);

  useEffect(() => {
    const action = actions[animation];
    if (action) {
      action.reset().fadeIn(0.5).play();
      return () => action.fadeOut(0.5);
    }
  }, [animation, actions]);

 
  return <primitive ref={group} object={clone} {...props} />;
}

useGLTF.preload("models/AvatarYanaContact.glb");