/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/EducationRoom.glb -o src/components/EducationRoom.jsx --transform 
Files: public/models/EducationRoom.glb [123.57MB] > C:\React\Portfolio_Yana_Naydenova — копия\Portfolio\src\components\EducationRoom-transformed.glb [4.57MB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function EducationRoom(props) {
  const { nodes, materials } = useGLTF('models/EducationRoom.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Hiko_Side_Table.geometry} material={materials['FUNITURE_039_MAT.001']} position={[-0.873, -0.139, -2.368]} rotation={[Math.PI / 2, 0, 0]} scale={[0.045, 0.032, 0.038]} />
      <mesh geometry={nodes.pCube4_Handles_and_support_0.geometry} material={materials['Handles_and_support.002']} position={[-1.032, -0.001, 0.286]} rotation={[Math.PI, -0.012, Math.PI]} scale={[0.095, 0.123, 0.106]} />
      <mesh geometry={nodes.pCylinder10_Legs_0.geometry} material={materials['Legs.002']} position={[-1.032, -0.001, 0.286]} rotation={[Math.PI, -0.012, Math.PI]} scale={[0.095, 0.123, 0.106]} />
      <mesh geometry={nodes.polySurface217_Wheel_0.geometry} material={materials['Wheel.002']} position={[-1.032, -0.001, 0.286]} rotation={[Math.PI, -0.012, Math.PI]} scale={[0.095, 0.123, 0.106]} />
      <mesh geometry={nodes.polySurface44_Back_portion_0.geometry} material={materials['Back_portion.002']} position={[-1.032, -0.001, 0.286]} rotation={[Math.PI, -0.012, Math.PI]} scale={[0.095, 0.123, 0.106]} />
      <mesh geometry={nodes.polySurface44_Centre_piece_0.geometry} material={materials['Centre_piece.002']} position={[-1.032, -0.001, 0.286]} rotation={[Math.PI, -0.012, Math.PI]} scale={[0.095, 0.123, 0.106]} />
      <mesh geometry={nodes.polySurface44_Chair_eye_0.geometry} material={materials['Chair_eye.002']} position={[-1.032, -0.001, 0.286]} rotation={[Math.PI, -0.012, Math.PI]} scale={[0.095, 0.123, 0.106]} />
      <mesh geometry={nodes.polySurface44_Chair_leather_0.geometry} material={materials['Chair_leather.002']} position={[-1.032, -0.001, 0.286]} rotation={[Math.PI, -0.012, Math.PI]} scale={[0.095, 0.123, 0.106]} />
      <mesh geometry={nodes.polySurface44_White_portion_0.geometry} material={materials['material_0.002']} position={[-1.032, -0.001, 0.286]} rotation={[Math.PI, -0.012, Math.PI]} scale={[0.095, 0.123, 0.106]} />
      <mesh geometry={nodes.Bottom.geometry} material={materials['BottomBaked.001']} position={[-1.017, 2.774, -2.003]} scale={[1.887, 1.678, 1.432]} />
      <mesh geometry={nodes.Charghing_State_LED.geometry} material={materials.PaletteMaterial001} position={[-1.39, 2.77, -1.53]} scale={[1.887, 1.678, 1.432]} />
      <mesh geometry={nodes.Headphone_Port.geometry} material={materials.PaletteMaterial002} position={[-1.017, 2.774, -2.003]} scale={[1.887, 1.678, 1.432]} />
      <mesh geometry={nodes.Keycaps.geometry} material={materials['Keycaps.001']} position={[-1.012, 2.776, -1.922]} scale={[2.264, 1.678, 1.718]} />
      <mesh geometry={nodes.Laptop001.geometry} material={materials['Surface.002']} position={[-1.056, 2.769, -1.716]} scale={[2.304, 1.678, 1.748]} />
      <group position={[-1.012, 2.761, -2.205]} scale={[2.304, 1.678, 1.748]}>
        <mesh geometry={nodes.Cube017.geometry} material={materials['LaptopLid.001']} />
        <mesh geometry={nodes.Cube017_1.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials.PaletteMaterial004} />
      </group>
      <mesh geometry={nodes.Metal.geometry} material={materials.PaletteMaterial005} position={[-1.498, 2.761, -1.849]} scale={[1.887, 1.678, 1.432]} />
      <mesh geometry={nodes.Power_State_LED.geometry} material={materials.PaletteMaterial006} position={[-1.428, 2.77, -1.53]} scale={[1.887, 1.678, 1.432]} />
      <mesh geometry={nodes.USB_Ports.geometry} material={materials['Ports.001']} position={[-1.498, 2.761, -1.849]} scale={[1.887, 1.678, 1.432]} />
      <mesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials['Wolf3D_Eye.013']} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} position={[0, -0.001, 0]} scale={[1, 0.992, 1]} />
      <mesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials['Wolf3D_Eye.013']} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} position={[0, -0.001, 0]} scale={[1, 0.992, 1]} />
    </group>
  )
}

useGLTF.preload('models/EducationRoom.glb')
