/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Room6.glb -o src/components/Room6.jsx --force 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room6(props) {
  const { nodes, materials } = useGLTF('models/Room6.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, -0.345, -0.225]} rotation={[Math.PI / 2, 0, 0]} scale={[0.009, 0.008, 0.009]}>
        <group position={[-101.79, -263.079, -22.058]} scale={[5.218, 3.971, 4.122]}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials.FUNITURE_039_MAT} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
      </group>
      <group position={[-1.032, -0.001, 0.286]} rotation={[-Math.PI / 2, 0, -3.13]} scale={[9.498, 10.625, 12.266]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[11.308, 0, -5.141]}>
            <mesh geometry={nodes.mesh_3_instance_1.geometry} material={materials['Wheel.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          </group>
          <group position={[-7.157, 0, -7.838]}>
            <mesh geometry={nodes.mesh_3_instance_2.geometry} material={materials['Wheel.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          </group>
          <group position={[-1.485, 0, -18.826]}>
            <mesh geometry={nodes.mesh_3_instance_3.geometry} material={materials['Wheel.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          </group>
          <group position={[9.853, 0, -16.469]}>
            <mesh geometry={nodes.mesh_3_instance_4.geometry} material={materials['Wheel.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          </group>
          <mesh geometry={nodes.mesh_1.geometry} material={materials['Handles_and_support.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_2.geometry} material={materials['Legs.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_3_instance_0.geometry} material={materials['Wheel.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_4.geometry} material={materials['Back_portion.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_5.geometry} material={materials['Centre_piece.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_6.geometry} material={materials['Chair_eye.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_7.geometry} material={materials['Chair_leather.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_8.geometry} material={materials['material_0.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_9.geometry} material={materials['Centre_piece.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_10.geometry} material={materials['Chair_leather.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
          <mesh geometry={nodes.mesh_11.geometry} material={materials['material_0.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
      </group>
      <group position={[0.674, 2.954, -2.871]} rotation={[Math.PI / 2, 0, 0]} scale={[2.295, 2.868, 2.411]}>
        <mesh geometry={nodes.mesh_12.geometry} material={materials['textured_0.003']} position={[-60, -30.294, -74.994]} scale={0.007} />
      </group>
      <group position={[-1.017, 2.745, -1.905]} scale={[1.278, 1.136, 0.97]}>
        <group position={[0, 0.025, -0.102]} scale={1.477}>
          <mesh geometry={nodes.mesh_13.geometry} material={materials.BottomBaked} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
        <group position={[-0.291, 0.021, 0.387]} scale={1.477}>
          <mesh geometry={nodes.mesh_14.geometry} material={materials['Charging State']} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
        <group position={[0, 0.025, -0.102]} scale={1.477}>
          <mesh geometry={nodes.mesh_15.geometry} material={materials.BottomBaked} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
        <group position={[0, 0.025, -0.102]} scale={1.477}>
          <mesh geometry={nodes.mesh_16.geometry} material={materials.Bottom} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
        <group position={[0.004, 0.027, -0.018]} scale={[1.771, 1.477, 1.771]}>
          <mesh geometry={nodes.mesh_17.geometry} material={materials.Keycaps} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
        <group position={[-0.03, 0.021, 0.195]} scale={[1.803, 1.477, 1.803]}>
          <mesh geometry={nodes.mesh_18.geometry} material={materials['Surface.001']} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
        <group position={[0, 0.022, -0.242]} scale={0.307}>
          <group position={[0.015, -0.029, -0.223]} scale={[5.872, 4.81, 5.872]}>
            <group position={[-60, -30.294, -74.994]} scale={0.007}>
              <mesh geometry={nodes.mesh_19.geometry} material={materials.LaptopLid} />
              <mesh geometry={nodes.mesh_19_1.geometry} material={materials.Screen} />
              <mesh geometry={nodes.mesh_19_2.geometry} material={materials['Camera Glass']} />
            </group>
          </group>
        </group>
        <group position={[-0.376, 0.013, 0.057]} scale={1.477}>
          <mesh geometry={nodes.mesh_20.geometry} material={materials.Metal} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
        <group position={[-0.321, 0.021, 0.387]} scale={1.477}>
          <mesh geometry={nodes.mesh_21.geometry} material={materials['On State']} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
        <group position={[-0.037, 0.031, 0.322]} scale={[1.803, 1.477, 1.803]}>
          <mesh geometry={nodes.mesh_22.geometry} material={materials.TouchPad} position={[-60, -30.294, -74.994]} scale={0.007} />
        </group>
        <group position={[-0.376, 0.013, 0.057]} scale={1.477}>
          <group position={[-60, -30.294, -74.994]} scale={0.007}>
            <mesh geometry={nodes.mesh_23.geometry} material={materials.Ports} />
            <mesh geometry={nodes.mesh_23_1.geometry} material={materials.VGA} />
          </group>
        </group>
      </group>
      <group position={[0, -0.001, 0]} scale={[1, 0.992, 1]}>
        <mesh name="mesh_24" geometry={nodes.mesh_24.geometry} material={materials['Wolf3D_Eye.003']} morphTargetDictionary={nodes.mesh_24.morphTargetDictionary} morphTargetInfluences={nodes.mesh_24.morphTargetInfluences} position={[-60, -30.294, -74.994]} scale={0.007} />
      </group>
      <group position={[0, -0.001, 0]} scale={[1, 0.992, 1]}>
        <mesh name="mesh_25" geometry={nodes.mesh_25.geometry} material={materials['Wolf3D_Eye.003']} morphTargetDictionary={nodes.mesh_25.morphTargetDictionary} morphTargetInfluences={nodes.mesh_25.morphTargetInfluences} position={[-60, -30.294, -74.994]} scale={0.007} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Room6.glb')
