/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Room5.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room5(props) {
  const { nodes, materials } = useGLTF('models/Room5.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, -0.345, -0.225]} rotation={[Math.PI / 2, 0, 0]} scale={[0.009, 0.008, 0.009]}>
        <mesh geometry={nodes.Hiko_Side_Table.geometry} material={materials.FUNITURE_039_MAT} position={[-101.79, -263.079, -22.058]} scale={[5.218, 3.971, 4.122]} />
      </group>
      <group position={[-1.032, -0.001, 0.286]} rotation={[-Math.PI / 2, 0, -3.13]} scale={[9.498, 10.625, 12.266]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.pCube4_Handles_and_support_0.geometry} material={materials['Handles_and_support.001']} />
          <mesh geometry={nodes.pCylinder10_Legs_0.geometry} material={materials['Legs.001']} />
          <mesh geometry={nodes.polySurface217_Wheel_0.geometry} material={materials['Wheel.001']} />
          <mesh geometry={nodes.polySurface222_Wheel_0.geometry} material={materials['Wheel.001']} position={[11.308, 0, -5.141]} />
          <mesh geometry={nodes.polySurface223_Wheel_0.geometry} material={materials['Wheel.001']} position={[-7.157, 0, -7.838]} />
          <mesh geometry={nodes.polySurface224_Wheel_0.geometry} material={materials['Wheel.001']} position={[-1.485, 0, -18.826]} />
          <mesh geometry={nodes.polySurface225_Wheel_0.geometry} material={materials['Wheel.001']} position={[9.853, 0, -16.469]} />
          <mesh geometry={nodes.polySurface44_Back_portion_0.geometry} material={materials['Back_portion.001']} />
          <mesh geometry={nodes.polySurface44_Centre_piece_0.geometry} material={materials['Centre_piece.001']} />
          <mesh geometry={nodes.polySurface44_Chair_eye_0.geometry} material={materials['Chair_eye.001']} />
          <mesh geometry={nodes.polySurface44_Chair_leather_0.geometry} material={materials['Chair_leather.001']} />
          <mesh geometry={nodes.polySurface44_White_portion_0.geometry} material={materials['material_0.001']} />
          <mesh geometry={nodes.polySurface50_Centre_piece_0.geometry} material={materials['Centre_piece.001']} />
          <mesh geometry={nodes.polySurface50_Chair_leather_0.geometry} material={materials['Chair_leather.001']} />
          <mesh geometry={nodes.polySurface50_White_portion_0.geometry} material={materials['material_0.001']} />
        </group>
      </group>
      <group position={[-1.017, 2.745, -1.905]} scale={[1.278, 1.136, 0.97]}>
        <group position={[0, 0.022, -0.242]} scale={0.307}>
          <group position={[0.015, -0.029, -0.223]} scale={[5.872, 4.81, 5.872]}>
            <mesh geometry={nodes.Cube017.geometry} material={materials.LaptopLid} />
            <mesh geometry={nodes.Cube017_1.geometry} material={materials.Screen} />
            <mesh geometry={nodes.Cube017_2.geometry} material={materials['Camera Glass']} />
          </group>
        </group>
        <mesh geometry={nodes.Bottom.geometry} material={materials.BottomBaked} position={[0, 0.025, -0.102]} scale={1.477} />
        <mesh geometry={nodes.Charghing_State_LED.geometry} material={materials['Charging State']} position={[-0.291, 0.021, 0.387]} scale={1.477} />
        <mesh geometry={nodes.Disc_Reader.geometry} material={materials.BottomBaked} position={[0, 0.025, -0.102]} scale={1.477} />
        <mesh geometry={nodes.Headphone_Port.geometry} material={materials.Bottom} position={[0, 0.025, -0.102]} scale={1.477} />
        <mesh geometry={nodes.Keycaps.geometry} material={materials.Keycaps} position={[0.004, 0.027, -0.018]} scale={[1.771, 1.477, 1.771]} />
        <mesh geometry={nodes.Laptop001.geometry} material={materials['Surface.001']} position={[-0.03, 0.021, 0.195]} scale={[1.803, 1.477, 1.803]} />
        <mesh geometry={nodes.Metal.geometry} material={materials.Metal} position={[-0.376, 0.013, 0.057]} scale={1.477} />
        <mesh geometry={nodes.Power_State_LED.geometry} material={materials['On State']} position={[-0.321, 0.021, 0.387]} scale={1.477} />
        <mesh geometry={nodes.TouchPad.geometry} material={materials.TouchPad} position={[-0.037, 0.031, 0.322]} scale={[1.803, 1.477, 1.803]} />
        <group position={[-0.376, 0.013, 0.057]} scale={1.477}>
          <mesh geometry={nodes.Cube013.geometry} material={materials.Ports} />
          <mesh geometry={nodes.Cube013_1.geometry} material={materials.VGA} />
        </group>
      </group>
      <group position={[0.03, -0.001, 0.072]} rotation={[-1.581, -0.02, -0.252]} scale={[3.386, 3.433, 3.315]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.004, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['M_Coffee_Cup.002']} position={[-0.805, 0.842, -0.609]} scale={[1, 0.917, 1]} />
          </group>
          <group position={[-0.022, 0.089, -0.027]} rotation={[-0.058, -0.921, -1.062]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['M_Coffee_Spoon.002']} position={[-1.211, -0.382, 0.307]} scale={[0.943, 0.977, 1]} />
          </group>
        </group>
      </group>
      <mesh geometry={nodes.textured003.geometry} material={materials['textured_0.003']} position={[0.674, 2.954, -2.871]} rotation={[Math.PI / 2, 0, 0]} scale={[2.295, 2.868, 2.411]} />
      <group position={[0.454, 2.765, -2.354]} rotation={[3.082, -0.615, Math.PI]} scale={[0.117, 0.023, 0.188]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.pagina} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.capa} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.interior} />
      </group>
      <mesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials['Wolf3D_Eye.003']} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} position={[0, -0.001, 0]} scale={[1, 0.992, 1]} />
      <mesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials['Wolf3D_Eye.003']} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} position={[0, -0.001, 0]} scale={[1, 0.992, 1]} />
    </group>
  )
}

useGLTF.preload('models/Room5.glb')
